# Generated by Django 4.2.18 on 2026-03-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='body',
        ),
        migrations.AddField(
            model_name='campaign',
            name='body_html',
            field=models.TextField(blank=True, help_text='HTML version', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='body_text',
            field=models.TextField(default='', help_text='Plain text version'),
        ),
    ]
